//You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

class Solution {
    public char findTheDifference(String s, String t) {
        int h1[]=new int[26];
        Arrays.fill(h1,0);
        char  ch=' ';
        boolean bl=false;
            for(int i=0;i<t.length();i++){
            h1[t.charAt(i)-'a']++;
        }
        for(int i=0;i<s.length();i++){
            h1[s.charAt(i)-'a']--;
        }
       
        for(int i=0;i<h1.length;i++){
if(h1[i]!=0){
     ch=(char)(i+'a');
    bl=true;
    
}
}
     return ch;   
    
    }
}